apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spotify-api-server
  name: spotify-api-server
  namespace: mweb
spec:
  progressDeadlineSeconds: 600
  # TODO: Enable replica with persisted sessions.
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spotify-api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spotify-api-server
    spec:
      containers:
        - image: spotify-api-server
          imagePullPolicy: IfNotPresent
          name: spotify-api-server-ctner
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-api-server
  namespace: mweb
spec:
  selector:
    app: spotify-api-server
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
